public class AmberRoadResponse {
     public Attributes attributes{get;set;}
     public Id id {get;set;}
     public String companyName {get;set;}
     public String contactName {get;set;}
     public String secondaryContactName {get;set;}
     public String streetAddress1 {get;set;}
     public String streetAddress2 {get;set;}
     public String streetAddress3 {get;set;}
     public String city {get;set;}
     public String stateCode {get;set;}
     public String countryCode{get;set;}
     public String postalCode {get;set;}
     public String email {get;set;}
     public String ip {get;set;}
}