public class NetsuiteContact {
    
    public String id {get; set;}
    public String firstName {get; set;}
    public String lastName {get; set;}
    public String email {get; set;} 
    public String phone {get; set;}
    public String salutation {get; set;}
    public String jobLevel {get; set;}
    public String title {get; set;}
    public String mobilePhone {get; set;}
    public DateTime createdDate {get; set;}
    public DateTime lastUpdatedDate {get; set;}
    public Meta meta {get; set;}
}