public class PlatformRegistrationResponse {
     public Attributes attributes{get;set;}
     public Id id {get;set;}
     public String firstName {get;set;}
     public String lastName {get;set;}
     public String email {get;set;}
     public String phone {get;set;}
     public String company {get;set;}
     public String countryCode {get;set;}
     public String stateCode {get;set;}
     public String leadSource {get;set;}
     public String accessCode{get;set;}
     public String campaignId {get;set;}
     public String remoteIp {get;set;}
     public String language {get;set;}
     public Boolean consultant {get;set;}
     public Boolean canadaOptIn {get;set;}
     public String jobLevel {get;set;}
     public String title {get;set;}
     public String sourceName {get;set;}
     public String platformLeadId {get;set;}
     public String customerId{get;set;}
     public String orgId {get;set;}
     public String correlationId {get;set;}
     public String pageUrl{get;set;}
     public String region {get;set;}
}