public class RequestPublishResultResponse {
    public Attributes attributes{get;set;}
    public Id id {get;set;}
    public String companyName {get;set;}
    public String contactName {get;set;}
    public String secondaryContactName {get;set;}
    public String streetAddress1 {get;set;}
    public String streetAddress2 {get;set;}
    public String streetAddress3 {get;set;}
    public String city {get;set;}
    public String stateCode {get;set;}
    public String countryCode{get;set;}
    public String postalCode {get;set;}
    public String status {get;set;}
    // TODO: add these back when the Platform team can accomodate them
    //public String screeningDate {get;set;}
    //public String errorMessage {get;set;}
}